### ISSUE TITLE
What are these for?

### ISSUE THREAD

**Issue by trusktr** [meteor/node-stubs#1]
Document why default apps come with this. https://github.com/meteor/guide/issues/314

**Comment by Tim-W** [comment]
The only documentation I can find is "use this when you want to use npm packages on the client". Some explanation how the package works and what it does (not) accept would be useful.

**Comment by benjamn** [comment]
The `meteor-node-stubs` npm package provides browser-friendly implementations of Node's built-in modules, like `path`, `buffer`, `util`, etc, similar to the way Webpack, Browserify, and other bundlers handle built-in modules. Meteor's module system avoids actually bundling any stub modules (and their dependencies) if they are not used, so there is no cost to keeping `meteor-node-stubs` in the `dependencies`. In other words, leave `meteor-node-stubs` installed unless you really know what you're doing.

**Comment by filipenevola** [comment]
I've updated this in the guide as well https://guide.meteor.com/using-npm-packages.html#client-npm
