### ISSUE TITLE
The dependency git+https://github.com/meteor/readable-stream.git causes problems with yarn

### ISSUE THREAD

**Issue by scharf** [meteor/node-stubs#10]
["readable-stream": "git+https://github.com/meteor/readable-stream.git"](https://github.com/meteor/node-stubs/blob/45ed0bdb0ed3dc074fff8d471190f1898704a4a6/package.json#L27)

There is a [strange bug with yarn](https://github.com/yarnpkg/yarn/issues/1625), it complains about `git+https` and I wonder what the reason for this kind of dependency is.

**Comment by benjamn** [comment]
I'm aware of this problem (or a similar problem) on Windows. Are you on Windows?

Here's an example of the rationale that motivated this URL protocol: https://stackoverflow.com/a/17509764/128454

Do you have a suggestion for something different?

**Comment by brucejo75** [comment]
New [answer](https://stackoverflow.com/a/36986828/7669642) in that thread claims the issue has gone away.  And the original format should work.
