### ISSUE TITLE
[meteor 1.7] import "_stream_*" fail

### ISSUE THREAD

**Issue by brucejo75** [meteor/node-stubs#15]
Looks like `meteor npm install` installs `readable-stream` to the parent directory of `meteor-node-stubs` which breaks the mapping.

I think this is an issue of `npm` 5.8.0

### Repro
1. `meteor create project --release 1.7-rc.1`
2. `cd project`
3. `meteor npm install meteor-node-stubs`
4. Note that `readable-stream` cannot be found in `node_modules/meteor-node-stubs`.
5. try importing `_stream_duplex` for example and you will get a fail.

### Workaround
use `npm` 5.6.0 to do installs.

### Notes
From what I can tell this is an issue of referring to a package from github:
[ "readable-stream": "git+https://github.com/meteor/readable-stream.git",](https://github.com/meteor/node-stubs/blob/master/package.json#L26) in package.json.

- referring to npm registry files works as expected
- referring to local npm packages works as expected.

**Comment by benjamn** [comment]
This should be fixed if you run `meteor npm install meteor-node-stubs@latest` to install 0.4.1: fc83c29b09710376a9f9260a6c0d77982acc29ed, d52c306a225c8312a99d2035d3752193fd819457, d88681f2b04a92f428fa3ebe92f8ce81202e5970

Thanks for reporting this!
