### ISSUE TITLE
Is 1.0 ready for release?

### ISSUE THREAD

**Issue by ArchiCroc** [meteor/node-stubs#18]
I traced a dependency error in my project to an old version of vm-browserify in meteor-node-stubs.  Looks it was fixed in April in this commit 4d70f1938a9b2c10eebcda86702f626d0a53603d. Any plans to push the 1.0 release to NPM?

**Comment by filipenevola** [comment]
Version 1.0.0 is published https://www.npmjs.com/package/meteor-node-stubs/v/1.0.0
