### ISSUE TITLE
Please update elliptic depedency

### ISSUE THREAD

**Issue by quophyie** [meteor/node-stubs#19]
Hi, 
We depend on `meteor-node-stubs` for one of our projects. `meteor-node-stubs`  seems to have a dependency on `elliptic` which according our security reports from snyk has a vulnerability so can you please update the `elliptic` dependency to a version newer elliptic than elliptic@6.4.0

Our security report is below

**Vulnerable module: elliptic**
Introduced through: meteor-node-stubs@0.4.1

**Detailed paths**
Introduced through: reaction@2.8.0 › meteor-node-stubs@0.4.1 › crypto-browserify@3.12.0 › create-ecdh@4.0.3 › elliptic@6.4.0

**Remediation:** Your dependencies are out of date, otherwise you would be using a newer elliptic than elliptic@6.4.0. Try relocking your lockfile or deleting node_modules, reinstalling and running snyk wizard. If the problem persists, one of your dependencies may be bundling outdated modules.

**Introduced through**: reaction@2.8.0 › meteor-node-stubs@0.4.1 › crypto-browserify@3.12.0 › browserify-sign@4.0.4 › elliptic@6.4.0
Remediation: Your dependencies are out of date, otherwise you would be using a newer elliptic than elliptic@6.4.0. Try relocking your lockfile or deleting node_modules, reinstalling and running snyk wizard. If the problem persists, one of your dependencies may be bundling outdated modules.

**Comment by Zertz** [comment]
If you're using Yarn, you can use [selective dependency resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to update sub-dependencies.

**Comment by filipenevola** [comment]
Hi @quophyie as our direct dependencies are up-to-date I believe the best option is really to use selective dependency resolutions from Yarn.

**Comment by namirsab** [comment]
Are there any plans on bumping the top level dependencies here to avoid the selective dependency resolution workaround?

**Comment by Zertz** [comment]
The issue comes from unmaintained dependencies.

`crypto-browserify` and `create-ecdh` haven't been updated in years. There's a [pull request](https://github.com/crypto-browserify/createECDH/pull/16) to update elliptic which you may 👍  to show support.
