### ISSUE TITLE
Missing url.URL constructor 

### ISSUE THREAD

**Issue by hexsprite** [meteor/node-stubs#20]
Just noticed that some of my client side tests were failing due to a missing URL constructor in the url package.

Thankfully the fix is pretty easy since it exists as window.URL

**Comment by Floriferous** [comment]
This doesn't seem related at all, but we've struggled with this package on our CI for the last few days. It can't find required node_modules, and this module seems to be random, it changes on every run

```sh
npm ERR! enoent ENOENT: no such file or directory, open '/home/circleci/app/microservices/app/node_modules/meteor-node-stubs/node_modules/buffer-xor/package.json'
 
npm ERR! enoent ENOENT: no such file or directory, open '/home/circleci/app/microservices/admin/node_modules/meteor-node-stubs/node_modules/des.js/package.json'
 
npm ERR! enoent ENOENT: no such file or directory, open '/home/circleci/app/microservices/admin/node_modules/meteor-node-stubs/node_modules/pako/package.json'
```

Could there be a link?

**Comment by hexsprite** [comment]
@Floriferous It sounds like a different issue.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
