### ISSUE TITLE
Update node-stubs to latest packages?

### ISSUE THREAD

**Issue by brucejo75** [meteor/node-stubs#28]
Hi, I have noticed that many of the node-stubs packages have updated versions.  How often does this package synchronize with the latest versions of the browserified node packages?

If you want an update on these, let me know and I can pull together a PR.

**Comment by StorytellerCZ** [comment]
@brucejo75 go ahead with the PR!

**Comment by brucejo75** [comment]
@StorytellerCZ, submitted #29 

My only real test was to integrate with my project and make sure it works.
