### ISSUE TITLE
How to use this in a meteor package.

### ISSUE THREAD

**Issue by ziedmahdi** [meteor/node-stubs#3]
I'm developing a meteor package that depend on typeaheadjs. So how to import typeahead from npm?

**Comment by abernix** [comment]
It's not related to this repository; you don't necessarily need this package (though in general, all Meteor applications have/should have this in their `dependencies`).  Please see [the Meteor Guide article](https://guide.meteor.com/using-npm-packages.html) on using packages from npm.

(hint: it's the same as in other bundlers: install the npm, and require the module in your code! 😄)
