### ISSUE TITLE
Generate shrinkwrap with NPM 3.x

### ISSUE THREAD

**Issue by ramijarrar** [meteor/node-stubs#4]
The package is currently an unavoidable source of deep nesting - we can solve this by removing/regenerating shrinkwrap in npm 3.x

**Comment by benjamn** [comment]
Probably due for some dependency version upgrades, too!

**Comment by benjamn** [comment]
Should we get rid of `npm-shrinkwrap.json` altogether, so that dependencies can be shared with other packages in an app's `node_modules` directory?

**Comment by ramijarrar** [comment]
That would be the ideal solution.

**Comment by ramijarrar** [comment]
And on a separate note: this is also a major problem for atmosphere NPM deps (not sure if there is any way to circumvent this without the support of package authors)
