### ISSUE TITLE
Updating to 1.4.4.3 causes ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by raphaelarias** [meteor/node-stubs#5]
When I updated from 1.4.4.2 to 1.4.4.3 I starting to get the error. I tried to replicate with an repo but I couldn't.

I'm using the 0.2.3 version, but I tried different ones.

As soon as my app finish to update to the latest version of Meteor and the meteor core apps, it stopped working. If I switch branches (for the ones that are not in the latest version) or downgrade the Meteor app, everything works.

Would you know what's going on or how can I solve/help with this issue?

<img width="1440" alt="screen shot 2017-05-31 at 4 54 07 pm" src="https://cloud.githubusercontent.com/assets/5008166/26620231/47083342-4625-11e7-86cc-ce73eba62880.png">

**Comment by benjamn** [comment]
Sorry for the inconvenience, but we thought it was worth saving you 22kB of minified JS: https://github.com/meteor/meteor/issues/8645#issuecomment-298349964. If you actually need `Buffer` on the client, see that comment for a workaround. If you don't, then you'll save a lot of unnecessary code!

**Comment by rgnevashev** [comment]
![2017-05-31_20-30-26](https://cloud.githubusercontent.com/assets/123600/26645216/0637eff4-4640-11e7-8f4f-9d444a7c30d3.png)

**Comment by raphaelarias** [comment]
It does make sense and I think it's worth to save 22kb. I'll take a look, but as far as I remember we don't need Buffer in the client side, only server side. It's probably another package.

**Comment by rgnevashev** [comment]
https://github.com/meteor/meteor/issues/8645#issuecomment-305218365

**Comment by dnish** [comment]
@benjamn Isn't meteor-node-stubs a core package? So you remove Buffer while using it in a core package which is added on every new Meteor project (https://github.com/meteor/guide/issues/314) by default. Why do you not add it automatically in the node-stubs package, so if I don't need node-stubs, Buffer will be also removed.

**Comment by benjamn** [comment]
@dnish I definitely agree the `Buffer` polyfill should go away when nothing that uses it is being imported. I think the problem here is that the `crypto` polyfill assumes a global `Buffer` constructor exists, when it should be using `require("buffer").Buffer` instead, to be safe.

**Comment by benjamn** [comment]
This should be fixed now, since I forked the problematic packages and dealt with the `Buffer` references. Let me know how it goes!
