### ISSUE TITLE
published shrinkwrap.json 

### ISSUE THREAD

**Issue by pociej** [meteor/node-stubs#7]
Is there any good reason to have shrinkwrap.json published ?  
https://docs.npmjs.com/files/shrinkwrap.json  says 

```
It's strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.
```

**Comment by benjamn** [comment]
We're using a `package-lock.json` file now, which is never published to npm: https://github.com/meteor/node-stubs/commit/f64e023202f1b19b78af2c7b6bdbbe12e868627f

We're still using [`bundledDependencies`](https://github.com/meteor/node-stubs/blob/998d5a746bce094a33ce506480b212659bf41a3e/package.json#L36), though, so `meteor-node-stubs/node_modules` will still contain the direct dependencies.
